### ISSUE TITLE
Spring integration requires scala-reflect at runtime

### ISSUE THREAD

**Issue by holograph** [wix/accord#30]
Per internal investigation within Wix, it's possible that the Spring integration (the default implementation of which relies on runtime reflection to map types to validators) indirectly requires scala-reflect at runtime; this was not the case for 2.10, and is a possible breaking change with 2.11. The suspected stack trace (sanitized) is as follows:

```
Caused by: java.lang.NoClassDefFoundError: scala/reflect/api/Exprs
    at java.lang.Class.getDeclaringClass0(Native Method)
    at java.lang.Class.getDeclaringClass(Class.java:1106)
    at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(ParameterizedTypeImpl.java:52)
    at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(ParameterizedTypeImpl.java:95)
    at sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(CoreReflectionFactory.java:105)
    at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:140)
    at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
    at sun.reflect.generics.repository.MethodRepository.getReturnType(MethodRepository.java:68)
    at java.lang.reflect.Method.getGenericReturnType(Method.java:245)
    at com.wix.accord.spring.CompanionObjectAccordValidatorResolver$GenericReturnType$.unapply(AccordValidatorResolver.scala:56)
    at com.wix.accord.spring.CompanionObjectAccordValidatorResolver$$anonfun$lookupValidator$1$$anonfun$apply$1.applyOrElse(AccordValidatorResolver.scala:73)
    at com.wix.accord.spring.CompanionObjectAccordValidatorResolver$$anonfun$lookupValidator$1$$anonfun$apply$1.applyOrElse(AccordValidatorResolver.scala:72)
    at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:141)
    at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:140)
    at scala.collection.Iterator$class.foreach(Iterator.scala:750)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
    at scala.collection.TraversableOnce$class.collectFirst(TraversableOnce.scala:132)
    at scala.collection.mutable.ArrayOps$ofRef.collectFirst(ArrayOps.scala:186)
    at com.wix.accord.spring.CompanionObjectAccordValidatorResolver$$anonfun$lookupValidator$1.apply(AccordValidatorResolver.scala:72)
    at com.wix.accord.spring.CompanionObjectAccordValidatorResolver$$anonfun$lookupValidator$1.apply(AccordValidatorResolver.scala:71)
    at scala.Option.flatMap(Option.scala:171)
    at com.wix.accord.spring.CompanionObjectAccordValidatorResolver.lookupValidator(AccordValidatorResolver.scala:71)
    at com.wix.accord.spring.AccordEnabledLocalValidationFactory.internalValidate(AccordEnabledLocalValidationFactory.scala:31)
    at com.wix.accord.spring.AccordEnabledLocalValidationFactory.validate(AccordEnabledLocalValidationFactory.scala:38)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
    at com.sun.proxy.$Proxy85.notifyTenant(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    ... 39 common frames omitted
```

**Comment by holograph** [comment]
Evidently this applies to Scala 2.10.3 as well, but was masked by scala-reflect being transitively added to the test configuration via ScalaTest. I'll add a separate build configuration with a repro case and figure out the right solution for it.

**Comment by holograph** [comment]
As an interim workaround, just add scala-reflect to your project and track this issue for updates.

**Comment by holograph** [comment]
Failed to reproduce issue (see latest commits on branch issue-30, if you're interested). Closing.
