### ISSUE TITLE
Macro transformation barfs on partial function sugar

### ISSUE THREAD

**Issue by holograph** [wix/accord#59]
When compiling the following code (derived while testing for possible workarounds for #58), the transformation barfs at compile time:

```scala
  def conditional[T, C](cond: =>C)(pf: PartialFunction[C, Validator[T]]): Validator[T] = new Validator[T] {
    override def apply(v1: T): Result = {
      val target =
        pf.applyOrElse(cond, c => new com.wix.accord.combinators.Fail[T]("Cannot match conditional value " + c))
      target(v1)
    }
  }

  import com.wix.accord.dsl._
  val vt = validator[Test] { t =>
    t.n is conditional(t.p) {
      case 0 => t.n is empty
      case 1 => t.n should startWith("test")
    }
  }
```

Resulting error:
```
[error] /Users/tomerga/dev/accord/core/src/test/scala/com/wix/accord/Issue58Test.scala:35: exception during macro expansion:
[error] java.lang.ClassCastException: scala.reflect.internal.Trees$Block cannot be cast to scala.reflect.api.Trees$CaseDefApi
[error] 	at scala.reflect.api.Trees$Transformer$$anonfun$transformCaseDefs$1.apply(Trees.scala:2581)
[error] 	at scala.reflect.api.Trees$Transformer$$anonfun$transformCaseDefs$1.apply(Trees.scala:2581)
[error] 	at scala.collection.immutable.List.loop$1(List.scala:172)
[error] 	at scala.collection.immutable.List.mapConserve(List.scala:188)
[error] 	at scala.reflect.api.Trees$Transformer.transformCaseDefs(Trees.scala:2581)
[error] 	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1375)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error] 	at com.wix.accord.transform.PatternHelper$$anon$3.transform(PatternHelper.scala:107)
[error] 	at scala.reflect.internal.Trees$$anonfun$itransform$2.apply(Trees.scala:1356)
[error] 	at scala.reflect.internal.Trees$$anonfun$itransform$2.apply(Trees.scala:1354)
[error] 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600)
[error] 	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1353)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error] 	at com.wix.accord.transform.PatternHelper$$anon$3.transform(PatternHelper.scala:107)
[error] 	at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2589)
[error] 	at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2587)
[error] 	at scala.collection.immutable.List.loop$1(List.scala:172)
[error] 	at scala.collection.immutable.List.mapConserve(List.scala:188)
[error] 	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587)
[error] 	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1397)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error] 	at com.wix.accord.transform.PatternHelper$$anon$3.transform(PatternHelper.scala:107)
[error] 	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2563)
[error] 	at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1401)
[error] 	at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1400)
[error] 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600)
[error] 	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1399)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error] 	at com.wix.accord.transform.PatternHelper$$anon$3.transform(PatternHelper.scala:107)
[error] 	at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2589)
[error] 	at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2587)
[error] 	at scala.collection.immutable.List.loop$1(List.scala:172)
[error] 	at scala.collection.immutable.List.mapConserve(List.scala:188)
[error] 	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587)
[error] 	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1359)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error] 	at com.wix.accord.transform.PatternHelper$$anon$3.transform(PatternHelper.scala:107)
[error] 	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1393)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error] 	at com.wix.accord.transform.PatternHelper$$anon$3.transform(PatternHelper.scala:107)
[error] 	at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2559)
[error] 	at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2559)
[error] 	at scala.collection.immutable.List.loop$1(List.scala:172)
[error] 	at scala.collection.immutable.List.mapConserve(List.scala:188)
[error] 	at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2559)
[error] 	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1340)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error] 	at com.wix.accord.transform.PatternHelper$$anon$3.transform(PatternHelper.scala:107)
[error] 	at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2559)
[error] 	at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2559)
[error] 	at scala.collection.immutable.List.loop$1(List.scala:172)
[error] 	at scala.collection.immutable.List.mapConserve(List.scala:188)
[error] 	at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2559)
[error] 	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1340)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error] 	at com.wix.accord.transform.PatternHelper$$anon$3.transform(PatternHelper.scala:107)
[error] 	at com.wix.accord.transform.PatternHelper$class.transformByPattern(PatternHelper.scala:108)
[error] 	at com.wix.accord.transform.ValidationTransform.transformByPattern(ValidationTransform.scala:40)
[error] 	at com.wix.accord.transform.ValidationTransform$$anonfun$2.applyOrElse(ValidationTransform.scala:117)
[error] 	at com.wix.accord.transform.ValidationTransform$$anonfun$2.applyOrElse(ValidationTransform.scala:115)
[error] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[error] 	at com.wix.accord.transform.ValidationTransform$$anonfun$1.applyOrElse(ValidationTransform.scala:109)
[error] 	at com.wix.accord.transform.ValidationTransform$$anonfun$1.applyOrElse(ValidationTransform.scala:109)
[error] 	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:162)
[error] 	at com.wix.accord.transform.PatternHelper$$anon$2.traverse(PatternHelper.scala:85)
[error] 	at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2484)
[error] 	at scala.reflect.internal.Trees$class.traverseComponents$1(Trees.scala:1227)
[error] 	at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1323)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[error] 	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
[error] 	at com.wix.accord.transform.PatternHelper$$anon$2.traverse(PatternHelper.scala:87)
[error] 	at com.wix.accord.transform.PatternHelper$class.collectFromPattern(PatternHelper.scala:89)
[error] 	at com.wix.accord.transform.ValidationTransform.collectFromPattern(ValidationTransform.scala:40)
[error] 	at com.wix.accord.transform.ValidationTransform.transformed(ValidationTransform.scala:126)
[error] 	at com.wix.accord.transform.ValidationTransform$.apply(ValidationTransform.scala:146)
[error]   implicit val v = validator[Test] { t =>
```

**Comment by holograph** [comment]
The solution for this as well as #58 is fundamentally the same (syntactic choices aside). Marking as duplicate.
