### ISSUE TITLE
`None.get` exception inside `dateOfBirth.isDefined` block very unexpected

### ISSUE THREAD

**Issue by zbeckman** [wix/accord#87]
This is a specific case (derived from comments on #81), but running into (more) problems with this date stuff. Given this:
```
    // p.dateOfBirth is Option[LocalDate]
    if (p.dateOfBirth.isDefined) {
      p.dateOfBirth.get isBefore LocalDate.now() as "date of birth is in the future" is true // <- None.get???
      p.dateOfBirth.get isAfter LocalDate.now().minusYears(150) as "birthdate must be less than 150 years ago" is true
    }
```
And most unexpectedly I'm getting a `None.get`:
```
java.util.NoSuchElementException: None.get
    at scala.None$.get(Option.scala:347)
    at scala.None$.get(Option.scala:345)
    at cx.trident.xiintegrate.validator.GuestDetailValidator$$anon$5.apply(GuestDetailValidator.scala:21)...
```
Also tried this, but same results (`None.get`):
```
    (p.dateOfBirth.nonEmpty is true) and (
        (p.dateOfBirth.get isBefore LocalDate.now() as "date of birth is in the future" is true) and
         (p.dateOfBirth.get isAfter LocalDate.now().minusYears(150) as "birthdate must be less than 150 years ago" is true)
     )
```
As a temporary but ugly workaround, I'm doing this:
```
      p.dateOfBirth.getOrElse(LocalDate.now()) isAfter LocalDate.now().minusYears(150) as "birthdate must be less than 150 years ago" is true
```

**Comment by zbeckman** [comment]
We are using Scala 2.11.8.

**Comment by zbeckman** [comment]
One more example of where this is an ugly little problem:
```
// TODO ZJB fix this, we want (but it throws an exception):
//    p.changeDate.map(_ isBefore LocalDate.now()).each as "change date cannot be in the future" is true
(p.changeDate.isDefined is false) or (p.changeDate.get isBefore LocalDate.now()) as "change date cannot be in the future" is true)
```

**Comment by holograph** [comment]
Works now with the latest merge to master! 0.6.1 will be out later this week including this fix.

**Comment by holograph** [comment]
Also, turns out this was a much bigger issue than expected (see changes in bug title)

**Comment by zbeckman** [comment]
Confirmed this is fixed in 0.7-SNAPSHOT. Thank you!!

**Comment by WebKoala** [comment]
Did you get round to publishing 6.1?  We are considering using the Accord library but we need this multiple if functionality.

(Awesome library btw, thanks for making this!)

**Comment by holograph** [comment]
Finishing touches, I expect it to be out in a day or two. You can test with
0.7-SNAPSHOT in the meantime, if you're interested...
