### ISSUE TITLE
java.lang.UnsupportedOperationException: Position.start on NoPosition when trying to use map

### ISSUE THREAD

**Issue by zbeckman** [wix/accord#89]
When working with validation around options, I tend to run into `java.lang.UnsupportedOperationException: Position.start on NoPosition` quite a bit. Here are two examples that trigger the exception:
```
// p.group.map(_) is a String
implicit val groupValidator = validator[Group] { (p: Group) =>
  p.group.map(_.length).each as "group length is not between 1 and 3 characters" is between(1, 3)
}
```
And another one (first discovered while discussing #81):
```
// p.dateOfBirth.map(_) is a LocalDate
p.dateOfBirth.map(_ isBefore LocalDate.now()).each as "date of birth is in the future" is true
```
The exception I'm seeing is:
```
Error:(11, 49) exception during macro expansion: 
java.lang.UnsupportedOperationException: Position.start on NoPosition
	at scala.reflect.internal.util.Position.fail(Position.scala:17)
	at scala.reflect.internal.util.UndefinedPosition.start(Position.scala:94)
	at scala.reflect.internal.util.UndefinedPosition.start(Position.scala:90)
	at com.wix.accord.transform.MacroHelper$class.startPos(MacroHelper.scala:70)
	at com.wix.accord.transform.ValidationTransform.startPos(ValidationTransform.scala:24)
	at com.wix.accord.transform.ExpressionDescriber$$anonfun$1.applyOrElse(ExpressionDescriber.scala:53)
	at com.wix.accord.transform.ExpressionDescriber$$anonfun$1.applyOrElse(ExpressionDescriber.scala:53)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.reflect.internal.Trees$CollectTreeTraverser.traverse(Trees.scala:1657)
	at scala.reflect.internal.Trees$CollectTreeTraverser.traverse(Trees.scala:1654)
	at scala.reflect.internal.Trees$$anonfun$traverseMemberDef$1$1.apply$mcV$sp(Trees.scala:1209)
	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2507)
	at scala.reflect.internal.Trees$class.traverseMemberDef$1(Trees.scala:1203)
	at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1328)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
	at scala.reflect.internal.Trees$CollectTreeTraverser.traverse(Trees.scala:1658)
	at scala.reflect.internal.Trees$CollectTreeTraverser.traverse(Trees.scala:1654)
	at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2484)
	at scala.reflect.api.Trees$Traverser.traverseParams(Trees.scala:2492)
	at scala.reflect.internal.Trees$$anonfun$itraverse$1.apply$mcV$sp(Trees.scala:1329)
	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2507)
	at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1329)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
	at scala.reflect.internal.Trees$CollectTreeTraverser.traverse(Trees.scala:1658)
	at scala.reflect.internal.Trees$CollectTreeTraverser.traverse(Trees.scala:1654)
	at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2484)
	at scala.reflect.internal.Trees$class.traverseComponents$1(Trees.scala:1284)
	at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1330)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
	at scala.reflect.internal.Trees$CollectTreeTraverser.traverse(Trees.scala:1658)
	at scala.reflect.internal.Trees$TreeContextApiImpl.collect(Trees.scala:118)
	at com.wix.accord.transform.ExpressionDescriber$class.prettyPrint(ExpressionDescriber.scala:53)
	at com.wix.accord.transform.ExpressionDescriber$class.describeTree(ExpressionDescriber.scala:127)
	at com.wix.accord.transform.ValidationTransform.describeTree(ValidationTransform.scala:24)
	at com.wix.accord.transform.ValidationTransform.rewriteOne(ValidationTransform.scala:41)
	at com.wix.accord.transform.ValidationTransform$$anonfun$rewriteValidationRules$1.applyOrElse(ValidationTransform.scala:192)
	at com.wix.accord.transform.ValidationTransform$$anonfun$rewriteValidationRules$1.applyOrElse(ValidationTransform.scala:190)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at com.wix.accord.transform.ValidationTransform$$anonfun$1.applyOrElse(ValidationTransform.scala:118)
	at com.wix.accord.transform.ValidationTransform$$anonfun$1.applyOrElse(ValidationTransform.scala:118)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at com.wix.accord.transform.ValidationTransform$$anonfun$3.applyOrElse(ValidationTransform.scala:144)
	at com.wix.accord.transform.ValidationTransform$$anonfun$3.applyOrElse(ValidationTransform.scala:144)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at com.wix.accord.transform.PatternHelper$$anon$2.traverse(PatternHelper.scala:85)
	at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2484)
	at scala.reflect.internal.Trees$class.traverseComponents$1(Trees.scala:1234)
	at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1330)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
	at com.wix.accord.transform.PatternHelper$$anon$2.traverse(PatternHelper.scala:87)
	at com.wix.accord.transform.PatternHelper$class.collectFromPattern(PatternHelper.scala:89)
	at com.wix.accord.transform.ValidationTransform.collectFromPattern(ValidationTransform.scala:24)
	at com.wix.accord.transform.ValidationTransform.transformed(ValidationTransform.scala:210)
	at com.wix.accord.transform.ValidationTransform$.apply(ValidationTransform.scala:230)
	implicit val groupValidator = validator[Group] { (p: Group) =>
```

**Comment by zbeckman** [comment]
We are using Scala 2.11.8.

**Comment by holograph** [comment]
Managed to reproduce the issue locally, thanks for the report. This looks like a simple one.

**Comment by zbeckman** [comment]
Confirmed that this is now working in 0.7-SNAPSHOT. Thanks a bunch!
